spring:
  application:
    name: library-records
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      fail-fast: true
  profiles:
    active: dev
